# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/cpp/shareMemQueue

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/cpp/shareMemQueue

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/cpp/shareMemQueue/CMakeFiles /data/cpp/shareMemQueue/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/cpp/shareMemQueue/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lsharememqueue

# Build rule for target.
lsharememqueue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsharememqueue
.PHONY : lsharememqueue

# fast build rule for target.
lsharememqueue/fast:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/build
.PHONY : lsharememqueue/fast

#=============================================================================
# Target rules for targets named sharememqueue

# Build rule for target.
sharememqueue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharememqueue
.PHONY : sharememqueue

# fast build rule for target.
sharememqueue/fast:
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/build
.PHONY : sharememqueue/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

src/FileLock.o: src/FileLock.cpp.o
.PHONY : src/FileLock.o

# target to build an object file
src/FileLock.cpp.o:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/FileLock.cpp.o
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/FileLock.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/FileLock.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/FileLock.cpp.o
.PHONY : src/FileLock.cpp.o

src/FileLock.i: src/FileLock.cpp.i
.PHONY : src/FileLock.i

# target to preprocess a source file
src/FileLock.cpp.i:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/FileLock.cpp.i
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/FileLock.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/FileLock.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/FileLock.cpp.i
.PHONY : src/FileLock.cpp.i

src/FileLock.s: src/FileLock.cpp.s
.PHONY : src/FileLock.s

# target to generate assembly for a file
src/FileLock.cpp.s:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/FileLock.cpp.s
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/FileLock.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/FileLock.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/FileLock.cpp.s
.PHONY : src/FileLock.cpp.s

src/FileLockGuard.o: src/FileLockGuard.cpp.o
.PHONY : src/FileLockGuard.o

# target to build an object file
src/FileLockGuard.cpp.o:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/FileLockGuard.cpp.o
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/FileLockGuard.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/FileLockGuard.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/FileLockGuard.cpp.o
.PHONY : src/FileLockGuard.cpp.o

src/FileLockGuard.i: src/FileLockGuard.cpp.i
.PHONY : src/FileLockGuard.i

# target to preprocess a source file
src/FileLockGuard.cpp.i:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/FileLockGuard.cpp.i
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/FileLockGuard.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/FileLockGuard.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/FileLockGuard.cpp.i
.PHONY : src/FileLockGuard.cpp.i

src/FileLockGuard.s: src/FileLockGuard.cpp.s
.PHONY : src/FileLockGuard.s

# target to generate assembly for a file
src/FileLockGuard.cpp.s:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/FileLockGuard.cpp.s
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/FileLockGuard.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/FileLockGuard.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/FileLockGuard.cpp.s
.PHONY : src/FileLockGuard.cpp.s

src/Notifier.o: src/Notifier.cpp.o
.PHONY : src/Notifier.o

# target to build an object file
src/Notifier.cpp.o:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/Notifier.cpp.o
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/Notifier.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Notifier.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Notifier.cpp.o
.PHONY : src/Notifier.cpp.o

src/Notifier.i: src/Notifier.cpp.i
.PHONY : src/Notifier.i

# target to preprocess a source file
src/Notifier.cpp.i:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/Notifier.cpp.i
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/Notifier.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Notifier.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Notifier.cpp.i
.PHONY : src/Notifier.cpp.i

src/Notifier.s: src/Notifier.cpp.s
.PHONY : src/Notifier.s

# target to generate assembly for a file
src/Notifier.cpp.s:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/Notifier.cpp.s
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/Notifier.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/Notifier.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/Notifier.cpp.s
.PHONY : src/Notifier.cpp.s

src/ShareMemQueue.o: src/ShareMemQueue.cpp.o
.PHONY : src/ShareMemQueue.o

# target to build an object file
src/ShareMemQueue.cpp.o:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/ShareMemQueue.cpp.o
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/ShareMemQueue.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/ShareMemQueue.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/ShareMemQueue.cpp.o
.PHONY : src/ShareMemQueue.cpp.o

src/ShareMemQueue.i: src/ShareMemQueue.cpp.i
.PHONY : src/ShareMemQueue.i

# target to preprocess a source file
src/ShareMemQueue.cpp.i:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/ShareMemQueue.cpp.i
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/ShareMemQueue.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/ShareMemQueue.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/ShareMemQueue.cpp.i
.PHONY : src/ShareMemQueue.cpp.i

src/ShareMemQueue.s: src/ShareMemQueue.cpp.s
.PHONY : src/ShareMemQueue.s

# target to generate assembly for a file
src/ShareMemQueue.cpp.s:
	$(MAKE) -f CMakeFiles/lsharememqueue.dir/build.make CMakeFiles/lsharememqueue.dir/src/ShareMemQueue.cpp.s
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/ShareMemQueue.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/ShareMemQueue.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/ShareMemQueue.cpp.s
.PHONY : src/ShareMemQueue.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/sharememqueue.dir/build.make CMakeFiles/sharememqueue.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/test/test1.o: src/test/test1.cpp.o
.PHONY : src/test/test1.o

# target to build an object file
src/test/test1.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/test/test1.cpp.o
.PHONY : src/test/test1.cpp.o

src/test/test1.i: src/test/test1.cpp.i
.PHONY : src/test/test1.i

# target to preprocess a source file
src/test/test1.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/test/test1.cpp.i
.PHONY : src/test/test1.cpp.i

src/test/test1.s: src/test/test1.cpp.s
.PHONY : src/test/test1.s

# target to generate assembly for a file
src/test/test1.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/test/test1.cpp.s
.PHONY : src/test/test1.cpp.s

src/test/test2.o: src/test/test2.cpp.o
.PHONY : src/test/test2.o

# target to build an object file
src/test/test2.cpp.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/test/test2.cpp.o
.PHONY : src/test/test2.cpp.o

src/test/test2.i: src/test/test2.cpp.i
.PHONY : src/test/test2.i

# target to preprocess a source file
src/test/test2.cpp.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/test/test2.cpp.i
.PHONY : src/test/test2.cpp.i

src/test/test2.s: src/test/test2.cpp.s
.PHONY : src/test/test2.s

# target to generate assembly for a file
src/test/test2.cpp.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/test/test2.cpp.s
.PHONY : src/test/test2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lsharememqueue"
	@echo "... rebuild_cache"
	@echo "... sharememqueue"
	@echo "... test1"
	@echo "... test2"
	@echo "... src/FileLock.o"
	@echo "... src/FileLock.i"
	@echo "... src/FileLock.s"
	@echo "... src/FileLockGuard.o"
	@echo "... src/FileLockGuard.i"
	@echo "... src/FileLockGuard.s"
	@echo "... src/Notifier.o"
	@echo "... src/Notifier.i"
	@echo "... src/Notifier.s"
	@echo "... src/ShareMemQueue.o"
	@echo "... src/ShareMemQueue.i"
	@echo "... src/ShareMemQueue.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/test/test1.o"
	@echo "... src/test/test1.i"
	@echo "... src/test/test1.s"
	@echo "... src/test/test2.o"
	@echo "... src/test/test2.i"
	@echo "... src/test/test2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

